### ISSUE TITLE
Install Directions Reference Nuclide Specific format-js-cli package

### ISSUE THREAD

**Issue by kevinastone** [kyldvs/format-js-sublime#1]
The install directions suggest to globally install `format-js-cli` which seems to be Nuclide specific:
https://github.com/kyldvs/format-js-cli/blob/master/bin/formatjs#L7-L8

**Comment by kevinastone** [comment]
So reading the source a bit further, it looks like this is intentional.  It's exposing some Nuclide codemod support in Sublime text.

**Comment by kyldvs** [comment]
Yeah, those packages are not nuclide specific, they are just open sourced via nuclide basically.
